const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"教研管理管理",
                        "menuJump":"列表",
                        "tableName":"jioayanguanli"
                    }
                ],
                "menu":"教研管理管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"教研人员管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"教研人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "报表"
                        ],
                        "menu":"教材管理",
                        "menuJump":"列表",
                        "tableName":"jiaocai"
                    }
                ],
                "menu":"教材管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "报表"
                        ],
                        "menu":"教研论文管理",
                        "menuJump":"列表",
                        "tableName":"lunwen"
                    }
                ],
                "menu":"教研论文管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "报表"
                        ],
                        "menu":"教研项目管理",
                        "menuJump":"列表",
                        "tableName":"xiangmu"
                    }
                ],
                "menu":"教研项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "报表"
                        ],
                        "menu":"教研资料管理",
                        "menuJump":"列表",
                        "tableName":"ziliao"
                    }
                ],
                "menu":"教研资料管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"教材类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJiaocai"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"教研论文类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLunwen"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"教研项目类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXiangmu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"教研资料类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZiliao"
                    }
                ],
                "menu":"基础数据管理"
            }
            /*,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"数据备份",
			            "menuJump":"列表",
			            "tableName":"beifen"
			        },
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"数据还原",
					    "menuJump":"列表",
					    "tableName":"huanyuan"
					}
			    ],
			    "menu":"数据库管理"
			}*/
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
            {
                "backMenu":[
                    {
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"教研人员管理",
                                "menuJump":"列表",
                                "tableName":"yonghu"
                            }
                        ],
                        "menu":"教研人员管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"教材管理",
                                "menuJump":"列表",
                                "tableName":"jiaocai"
                            }
                        ],
                        "menu":"教材管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"教研论文管理",
                                "menuJump":"列表",
                                "tableName":"lunwen"
                            }
                        ],
                        "menu":"教研论文管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"教研项目管理",
                                "menuJump":"列表",
                                "tableName":"xiangmu"
                            }
                        ],
                        "menu":"教研项目管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"教研资料管理",
                                "menuJump":"列表",
                                "tableName":"ziliao"
                            }
                        ],
                        "menu":"教研资料管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"公告管理",
                                "menuJump":"列表",
                                "tableName":"gonggao"
                            }
                        ],
                        "menu":"公告管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "删除",
                                    "修改"
                                ],
                                "menu":"公告类型管理",
                                "menuJump":"列表",
                                "tableName":"dictionaryGonggao"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "删除",
                                    "修改"
                                ],
                                "menu":"教材类型管理",
                                "menuJump":"列表",
                                "tableName":"dictionaryJiaocai"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "删除",
                                    "修改"
                                ],
                                "menu":"教研论文类型管理",
                                "menuJump":"列表",
                                "tableName":"dictionaryLunwen"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "删除",
                                    "修改"
                                ],
                                "menu":"教研项目类型管理",
                                "menuJump":"列表",
                                "tableName":"dictionaryXiangmu"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "删除",
                                    "修改"
                                ],
                                "menu":"教研资料类型管理",
                                "menuJump":"列表",
                                "tableName":"dictionaryZiliao"
                            }
                        ],
                        "menu":"基础数据管理"
                    }
                    /*,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"数据备份",
                                "menuJump":"列表",
                                "tableName":"beifen"
                            },
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"数据还原",
                                "menuJump":"列表",
                                "tableName":"huanyuan"
                            }
                        ],
                        "menu":"数据库管理"
                    }*/
                ],
                "frontMenu":[],
                "hasBackLogin":"是",
                "hasBackRegister":"否",
                "hasFrontLogin":"否",
                "hasFrontRegister":"否",
                "roleName":"教研管理",
                "tableName":"jioayanguanli"
            },
            {
                "backMenu":[
                    {
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                ],
                                "menu":"教材管理",
                                "menuJump":"列表",
                                "tableName":"jiaocai"
                            }
                        ],
                        "menu":"教材管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"教研论文管理",
                                "menuJump":"列表",
                                "tableName":"lunwen"
                            }
                        ],
                        "menu":"教研论文管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                ],
                                "menu":"教研项目管理",
                                "menuJump":"列表",
                                "tableName":"xiangmu"
                            }
                        ],
                        "menu":"教研项目管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                ],
                                "menu":"教研资料管理",
                                "menuJump":"列表",
                                "tableName":"ziliao"
                            }
                        ],
                        "menu":"教研资料管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                ],
                                "menu":"公告管理",
                                "menuJump":"列表",
                                "tableName":"gonggao"
                            }
                        ],
                        "menu":"公告管理"
                    }

                    /*,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"数据备份",
                                "menuJump":"列表",
                                "tableName":"beifen"
                            },
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"数据还原",
                                "menuJump":"列表",
                                "tableName":"huanyuan"
                            }
                        ],
                        "menu":"数据库管理"
                    }*/
                ],
                "frontMenu":[],
                "hasBackLogin":"是",
                "hasBackRegister":"否",
                "hasFrontLogin":"否",
                "hasFrontRegister":"否",
                "roleName":"教研人员",
                "tableName":"yonghu"
            }

]
    }
}
export default menu;
